name: Terraform Validate

on:
  push:
    branches: ["dev", "main"]
  pull_request:
  workflow_dispatch:

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Format
        run: |
          if ! terraform fmt -check; then
            echo "Terraform files are not formatted correctly."
            exit 1
          fi

          
